# Github Library
github:
  name: ComposeStyled
  release: 2025
  namespace: com.michaelflisar.composestyled
  license:
    name: Apache License 2.0
    path: blob/main/LICENSE

# Maven
maven:
  group-id: io.github.mflisar.composestyled
  primary-artifact-id: core # used to detect latest release version of the library (dynamically on the published homepage)

# Modules - list of modules [artifact-id, description, path]
modules:
  - artifact-id: core
    description: This is the core module
    path: library/core
  - artifact-id: components
    description: This is module providing various UI components
    path: library/components
  - artifact-id: theme-material3
    description: The material3 theme module based on compose-unstyled
    path: library/themes/material3
  - artifact-id: theme-cupertino
    description: The cupertino theme module based on compose-unstyled
    path: library/themes/cupertino
  - artifact-id: theme-fluent2
    description: The fluent2 theme module based on compose-unstyled
    path: library/themes/fluent2
  - artifact-id: themewrapper-material3
    description: The wrapper theme around androidx.compose.material3
    path: library/wrapperthemes/material3

# XCFrameworks [name, path, targets (ios, macos)]
xcframeworks: []